### ISSUE TITLE
Special on Monday

### ISSUE THREAD

**Issue by KimHyoJin** [babjo/what-day-bot#4]
월요일은 특별하니까, 오늘은 Monday입니다라는 문구대신 다음의 영상링크를 보내주면 좋을 것같습니다
https://www.youtube.com/watch?v=muoGoDiJIRk

**Comment by babjo** [comment]
감사합니다. 매주 월 그리고 명령어 '월요송' 이라고 입력하면 해당 영상을 보내주는 것으로 구현했습니다.
